-- INNER JOIN
-- RETORNA SOMENTE AS COLUNAS CORRESPONDENTES ENTRE AS TABELAS. 
-- COLUNA ID_CARRO NA TABELA PROPRIETARIO / ID NA TABELA CARRO
USE bd_carro;
SELECT * FROM tb_proprietario AS P
INNER JOIN tb_carros AS C
ON P.id_carro = C.id;

-- RIGHT JOIN
-- TODOS OS REGISTRO DA SEGUNDA TABELA SEJAM RETORNADAS, MESMO QUE NÃO HAJA SIMILARIDADE NA SEGUNDA TABELA.
SELECT * FROM tb_proprietario
RIGHT JOIN tb_carros
ON tb_proprietario.id_carro = tb_carros.id;

-- LEFT JOIN
-- VAI ME RETORNAR TODOS OS REGITROS DA PRIMEIRA TABELA (ESQUERDA), MAIS AS SIMILARIDADES DA SEGUNDA TABELA (DIREITA).
SELECT * FROM tb_carros
LEFT JOIN tb_proprietario
ON tb_carros.id = tb_proprietario.id_carro;

-- UNION
-- COMBINAÇÃO DOS DOIS JOIN (RIGHT E LEFT).
SELECT * FROM tb_proprietario AS P
LEFT JOIN tb_carros AS C
ON P.id_carro = C.id
UNION
SELECT * FROM tb_proprietario AS P
RIGHT JOIN tb_carros AS C
ON C.id = P.id_carro
WHERE P.id_carro IS NULL;